#!/bin/bash

# exit if any command fails and start from main project directory
set -e
cd "$(dirname "$0")/.."

echo "==> Installing node dependencies…"
npm install


echo "==> Patching shebang lines in node_modules/.bin…"

NODE_PREFIX="$(hab pkg path core/node)"

grep -nlI '^\#\!/usr/bin/env node' ./node_modules/.bin/* | while read -r target; do
    echo "$target"
    sed -e "s#\#\!/usr/bin/env node#\#\!${NODE_PREFIX}/bin/node#" --in-place --follow-symlinks "$target"
done

echo
