#!/bin/bash

# exit if any command fails and start from main project directory
set -e
cd "$(dirname "$0")/.."

# ensure dependencies are all available
script/bootstrap

# build frontend
node_modules/.bin/gulp run

# TODO: any needed data migrations
